# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - patchset/*

strategy:
  matrix:
    ubuntu_gcc5:
      imageName: 'ubuntu-16.04'
      tool_chain_tag: 'GCC5'
  maxParallel: 2

pool:
  vmImage: $(imageName)

steps:
- script: |
    export WORKSPACE=$PWD
    sudo apt-get install software-properties-common
    sudo add-apt-repository ppa:deadsnakes/ppa
    sudo apt-get update
    sudo apt-get install python3.7
    sudo apt-get install uuid-dev
    sudo apt-get install iasl
    sudo apt-get install nasm
    python --version
    gcc --version
    nasm --v
    iasl -v
    openssl version
#    git submodule update --init
#    make -C BaseTools
#    . edksetup.sh
#    build -a IA32 -a X64 -n 0 -t $(tool_chain_tag) -p OvmfPkg/OvmfPkgIa32X64.dsc -D SMM_REQUIRE -D DEBUG_ON_SERIAL_PORT
