# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master_pipeline

#  vmImage: 'vs2017-win2016'
pool:
  vmImage: 'vs2015-win2012r2'
  
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    python --version
  displayName: 'Run a multi-line script'

- script: |
    set WORKSPACE=%CD%
    set EDK_TOOLS_PATH=%WORKSPACE%\BaseTools
    git submodule update --init
    powershell "& {[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-WebRequest -Uri "https://www.python.org/ftp/python/3.7.4/python-3.7.4.exe -OutFile python-3.7.4.exe"}"
    python-3.7.4.exe /quiet InstallAllUsers=1 PrependPath=1 Include_test=0    
    powershell "& {[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-WebRequest -Uri "https://www.nasm.us/pub/nasm/releasebuilds/2.13.03/win64/nasm-2.13.03-win64.zip -OutFile nasm-2.13.03-win64.zip"}"
    powershell Expand-Archive nasm-2.13.03-win64.zip .
    set NASM_PREFIX=%WORKSPACE%\nasm-2.13.03\
    powershell "& {[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-WebRequest -Uri "https://acpica.org/sites/acpica/files/iasl-win-20190509.zip -OutFile iasl-win-20190509.zip"}"
    powershell Expand-Archive iasl-win-20190509.zip
    set IASL_PREFIX=%WORKSPACE%\iasl-win-20190509\
    path=%path%;%WORKSPACE%\openssl-1.0.2r-x64_86-win64
    call edkSetup.bat Rebuild
    build -a IA32 -a X64 -n 0 -t VS2015 -p OvmfPkg/OvmfPkgIa32X64.dsc -D DEBUG_ON_SERIAL_PORT
