# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - patchset/*

strategy:
  matrix:
    windows_vs2015:
      imageName: 'vs2017-win2016'
      tool_chain_tag: 'VS2015x86'
    windows_vs2017:
      imageName: 'vs2017-win2016'
      tool_chain_tag: 'VS2017'
    ubuntu_gcc5:
      imageName: 'ubuntu-16.04'
      tool_chain_tag: 'GCC5'
  maxParallel: 3

pool:
  vmImage: $(imageName)

steps:
- script: |
    git submodule update --init

- script: |
    set WORKSPACE=%CD%
    set EDK_TOOLS_PATH=%WORKSPACE%\BaseTools
    powershell "& {[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-WebRequest -Uri "https://www.nasm.us/pub/nasm/releasebuilds/2.13.03/win64/nasm-2.13.03-win64.zip -OutFile nasm-2.13.03-win64.zip"}"
    powershell Expand-Archive nasm-2.13.03-win64.zip .
    set NASM_PREFIX=%WORKSPACE%\nasm-2.13.03\
    powershell "& {[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-WebRequest -Uri "https://acpica.org/sites/acpica/files/iasl-win-20190509.zip -OutFile iasl-win-20190509.zip"}"
    powershell Expand-Archive iasl-win-20190509.zip
    set IASL_PREFIX=%WORKSPACE%\iasl-win-20190509\
    powershell "& {[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-WebRequest -Uri "https://indy.fulgan.com/SSL/openssl-1.0.2r-x64_86-win64.zip -OutFile openssl-1.0.2r-x64_86-win64.zip"}"
    powershell Expand-Archive openssl-1.0.2r-x64_86-win64.zip
    path=%path%;%WORKSPACE%\openssl-1.0.2r-x64_86-win64
    python --version
    cl
    %NASM_PREFIX%nasm --v
    %IASL_PREFIX%iasl -v
    openssl version
    call edkSetup.bat Rebuild
  condition: and (always(), eq(variables['Agent.OS'], 'Windows_NT'))

- script: |
    export WORKSPACE=$PWD
    sudo apt-get install uuid-dev
    sudo apt-get install iasl
    sudo apt-get install nasm
    python --version
    python3.6 --version
    python3.7 --version
    gcc --version
    nasm --v
    iasl -v
    openssl version
    make -C BaseTools
    . edksetup.sh
  condition: and (always(), eq(variables['Agent.OS'], 'Linux'))

- script: |
    export WORKSPACE=$PWD
    python --version
    gcc --version
    nasm --v
    iasl -v
    openssl version
    make -C BaseTools
    . edksetup.sh
  condition: and (always(), eq(variables['Agent.OS'], 'Darwin'))

- script: |
    build -a IA32 -a X64 -n 0 -t $(tool_chain_tag) -p OvmfPkg/OvmfPkgIa32X64.dsc -D SMM_REQUIRE -D DEBUG_ON_SERIAL_PORT
