## @file
# Manual GitHubAction to perform build comparison
#
# Copyright (c) 2021, Intel Corporation. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      repo:
        description: 'Public edk2 repository to use for comparison'
        default: 'mdkinney/edk2'
        required: true
      ref1:
        description: 'First git reference for comparison'
        default: ''
        required: true
      ref2:
        description: 'Second git reference for comparison'
        default: ''
        required: true
      buildoptions:
        description: 'Extra options to add to end of build command (e.g. --quiet, --verbose)'
        default: '-n 4 --quiet'
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  gcc_compare:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./edk2

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
      with:
        name: mdkinney/edk2
        ref: sandbox/CompareBuild
        path: compare
        submodules: false
    - uses: actions/checkout@v2
      with:
        name: ${{ github.event.inputs.repo }}
        ref: ${{ github.event.inputs.ref2 }}
        path: edk2
        submodules: false
    - uses: actions/checkout@v2
      with:
        name: ${{ github.event.inputs.repo }}
        ref: ${{ github.event.inputs.ref1 }}
        path: edk2
        submodules: true
    - run: |
        python -m pip install --upgrade pip
        pip install GitPython
    - run: |
        curl -k -O  -L http://ftp.us.debian.org/debian//pool/main/n/nasm/nasm_2.15.05-1_amd64.deb
        sudo apt install ./nasm_2.15.05-1_amd64.deb
        nasm --version
    - run: |
        sudo apt-get upgrade
        sudo apt-get update
        sudo apt-get install make gcc uuid-dev iasl python3-pip gcc-arm-none-eabi gcc-riscv64-linux-gnu gcc-aarch64-linux-gnu pax-utils
    - run: |
        . edksetup.sh
        make -C BaseTools
        export GCC5_AARCH64_PREFIX="/usr/bin/aarch64-linux-gnu-"
        export GCC5_ARM_PREFIX="/usr/bin/arm-none-eabi-"
        export GCC5_RISCV64_PREFIX="/usr/bin/riscv64-linux-gnu-"
        python3 ../compare/CompareBuild.py --ref1 ${{ github.event.inputs.ref1 }} --ref2 ${{ github.event.inputs.ref2 }} build -t GCC5 -j Build/Build.log -a IA32 -b NOOPT -p FatPkg/FatPkg.dsc ${{ github.event.inputs.buildoptions }}
        python3 ../compare/CompareBuild.py --ref1 ${{ github.event.inputs.ref1 }} --ref2 ${{ github.event.inputs.ref2 }} build -t GCC5 -j Build/Build.log -a X64 -b NOOPT -p FatPkg/FatPkg.dsc ${{ github.event.inputs.buildoptions }}
        python3 ../compare/CompareBuild.py --ref1 ${{ github.event.inputs.ref1 }} --ref2 ${{ github.event.inputs.ref2 }} build -t GCC5 -j Build/Build.log -a ARM -b NOOPT -p FatPkg/FatPkg.dsc ${{ github.event.inputs.buildoptions }}
        python3 ../compare/CompareBuild.py --ref1 ${{ github.event.inputs.ref1 }} --ref2 ${{ github.event.inputs.ref2 }} build -t GCC5 -j Build/Build.log -a AARCH64 -b NOOPT -p FatPkg/FatPkg.dsc ${{ github.event.inputs.buildoptions }}
        python3 ../compare/CompareBuild.py --ref1 ${{ github.event.inputs.ref1 }} --ref2 ${{ github.event.inputs.ref2 }} build -t GCC5 -j Build/Build.log -a RISCV64 -b NOOPT -p FatPkg/FatPkg.dsc ${{ github.event.inputs.buildoptions }}
    - run: ls -al
