## @file
# Manual GitHubAction to perform build comparison
#
# Copyright (c) 2021, Intel Corporation. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      ref1:
        description: 'First git reference for comparison'
        default: ''
        required: true
      ref2:
        description: 'Second git reference for comparison'
        default: ''
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  gcc_compare:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@V2
      with:
        name: mdkinney/edk2
        ref: sandbox/CompareBuild
        path: compare
        submodules: false
    - uses: actions/checkout@V2
      with:
        name: mdkinney/edk2
        path: edk2
        submodules: true
    - run: apt-get install make gcc uuid-dev iasl nasm python3-pip gcc-arm-none-eabi gcc-riscv64-linux-gnu gcc-aarch64-linux-gnu pax-utils
    - run: cd edk2
    - run: . edksetup.sh
    - run: python3 ../compare/CompareBuild.py --ref1 ${{ github.event.inputs.ref1 }} --ref2 ${{ github.event.inputs.ref2 }} build -n 4 -t GCC5 -j Build/Build.log -a ARM -b NOOPT -p ArmPkg/ArmPkg.dsc --quiet
