## @file
# Manual GitHubAction to perform build of package documentation
#
# Copyright (c) 2021, Intel Corporation. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

name: Build package documentation

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      repo:
        description: 'Public edk2 repository sources used to build package documentation'
        default: 'mdkinney/edk2'
        required: true
      ref:
        description: 'Git branch/tag/sha sources used to build package documentation'
        default: ''
        required: true
      publish_repo:
        description: 'Public edk2 repository used to publish package documentation'
        default: 'mdkinney/edk2'
        required: true
      publish_branch:
        description: 'Git branch to publish package documentation'
        default: 'gh-pages'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  gcc_build_package_documents:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
      with:
        repository: ${{ github.event.inputs.repo }}
        ref: ${{ github.event.inputs.ref }}
        path: edk2
        submodules: false
    - name: Install Doxygen 1.8.6
      run: |
        curl -o ./doxygen.deb http://launchpadlibrarian.net/163827726/doxygen_1.8.6-2_amd64.deb
        sudo apt install ./doxygen.deb
        rm ./doxygen.deb
        /usr/bin/doxygen --version
    - name: Build HTML package documents
      run: |
        cd edk2
        . edksetup.sh
        echo "<!DOCTYPE html>"                                           > $WORKSPACE/Build/Doxygen/index.html
        echo "<html>"                                                   >> $WORKSPACE/Build/Doxygen/index.html
        echo "  <head>"                                                 >> $WORKSPACE/Build/Doxygen/index.html
        echo "    <title>EDK II Package Doxygen Documentation</title>"  >> $WORKSPACE/Build/Doxygen/index.html
        echo "  </head>"                                                >> $WORKSPACE/Build/Doxygen/index.html
        echo "  <body>"                                                 >> $WORKSPACE/Build/Doxygen/index.html
        echo "    <h1>EDK II Package Doxygen Documentation</h1>"        >> $WORKSPACE/Build/Doxygen/index.html
        for Pkg in \
          ArmPkg \
          ArmPlatformPkg \
          ArmVirtPkg \
          CryptoPkg \
          DynamicTablesPkg \
          EmbeddedPkg \
          EmulatorPkg \
          FatPkg \
          FmpDevicePkg \
          IntelFsp2Pkg \
          IntelFsp2WrapperPkg \
          MdeModulePkg \
          MdePkg \
          NetworkPkg \
          OvmfPkg \
          PcAtChipsetPkg \
          RedfishPkg \
          SecurityPkg \
          ShellPkg \
          SignedCapsulePkg \
          SourceLevelDebugPkg \
          StandaloneMmPkg \
          UefiCpuPkg \
          UefiPayloadPkg \
          UnitTestFrameworkPkg
        do
          python3 BaseTools/Scripts/PackageDocumentTools/packagedoc_cli.py -w $WORKSPACE -p $WORKSPACE/$Pkg/$Pkg.dec -x /usr/bin/doxygen -a ALL -i -o $WORKSPACE/Build/Doxygen/$Pkg
          echo "    <a href=\"${Pkg}/html/index.html\">${Pkg}</a><br>"       >> $WORKSPACE/Build/Doxygen/index.html
        done
        echo "  </body>"       >> $WORKSPACE/Build/Doxygen/index.html
        echo "</html>"       >> $WORKSPACE/Build/Doxygen/index.html
    - name: Publish HTML package documents
      run: |
        git clone -b ${{github.event.inputs.publish_branch}} https://${GITHUB_ACTOR}:${{secrets.GITBOOK_ACTION_PERSONAL_TOKEN}}@github.com/${{github.event.inputs.publish_repo}}.git Publish
        cp -rfp edk2/Build/Doxygen/. Publish
        cd Publish
        git config --local user.name  ${GITHUB_ACTOR}
        git config --local user.email ${GITHUB_ACTOR}@users.noreply.github.com
        git add .
        git commit -m "Publish package documentation"
        echo git push https://${GITHUB_ACTOR}:${{secrets.GITBOOK_ACTION_PERSONAL_TOKEN}}@github.com/${{github.event.inputs.publish_repo}}.git  ${{github.event.inputs.publish_branch}}:${{github.event.inputs.publish_branch}}
